swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.1.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update user profile
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get all transactions grouped by account
      description: Retrieve all transactions for the current month, grouped by account
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsGroupedResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /user/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get transaction details
      description: Retrieve detailed information about a specific transaction
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Transaction ID
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Patch transaction information
      description: Add, modify or remove specific optional information (e.g. note or category)
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Transaction ID
        - in: body
          name: body
          required: true
          description: Fields to update or delete
          schema:
            $ref: '#/definitions/TransactionPatch'
      responses:
        '200':
          description: Transaction patched successfully
        '400':
          description: Invalid patch data
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

  TransactionsGroupedResponse:
    type: array
    description: List of accounts with grouped transactions
    items:
      type: object
      properties:
        accountId:
          type: string
        accountName:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/definitions/Transaction'

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        pattern: '^\d{2}/\d{2}/\d{2}$'
        description: Date in DD/MM/YY format
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
        enum: [Electronic, Wire, Check, Card, Cash]
        description: Type of transaction
      category:
        type: string
        enum: [Food, Rent, Transport, Utilities, Others]
        description: User-defined category
      note:
        type: string
        maxLength: 256
        description: Optional note added by the user

  TransactionPatch:
    type: object
    description: At least one of the following fields is required
    properties:
      category:
        type: string
        enum: [Food, Rent, Transport, Utilities, Others]
      note:
        type: string
        maxLength: 256
